### ISSUE TITLE
uber-juno install fails in atom release 1.40

### ISSUE THREAD

**Issue by rryi** [JunoLab/uber-juno#73]
System: Win10 x64 2019H1.
Atom setup via ZIP file (portable installation)

I did install uber-juno in older atom releases, up to release 1.39.1, without problems.

In release 1.40, I get the error

```
Juno: Error installing package julia-client

Please check your internet connection, or report this to
    http://discuss.junolab.org
and we'll try to help.
    –––
Error: Installing “julia-client@0.9.4” failed.

```

I tried then to install julia-client, only.

It fails, displaying
`  Installing “julia-client@0.9.4” failed.Show output…`

the output:

```
> @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install R:\Temp\apm-install-dir-119714-10908-9jgein.rbpwc\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt
> prebuild-install || node scripts/install.js


R:\Temp\apm-install-dir-119714-10908-9jgein.rbpwc\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt>if not defined npm_config_node_gyp (node "C:\RRtool\Atom\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\RRtool\Atom\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\RRtool\Atom\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\RRtool\Atom\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\RRtool\Atom\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\RRtool\\Atom\\resources\\app\\apm\\bin\\node.exe" "C:\\RRtool\\Atom\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd R:\Temp\apm-install-dir-119714-10908-9jgein.rbpwc\node_modules\julia-client\node_modules\@pfitzseb\node-pty-prebuilt
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'R:\Temp\apm-install-dir-119714-10908-9jgein.rbpwc\package.json'
npm WARN apm-install-dir-119714-10908-9jgein.rbpwc No description
npm WARN apm-install-dir-119714-10908-9jgein.rbpwc No repository field.
npm WARN apm-install-dir-119714-10908-9jgein.rbpwc No README data
npm WARN apm-install-dir-119714-10908-9jgein.rbpwc No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install: `prebuild-install || node scripts/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @pfitzseb/node-pty-prebuilt@0.8.1-prebuilt3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\RR\.atom\.apm\_logs\2019-08-14T18_39_33_262Z-debug.log

```

**Comment by BioTurboNick** [comment]
May be related--I just updated Atom to 1.40.0 (from ~1.28 I think) and the Juno elements disappeared. Tried uninstalling and reinstalling Juno and no luck. No error, packages show as installed, just no Juno UI.

**Comment by pfitzseb** [comment]
Going to close this since it's in the wrong place.
Please follow the progress [here](https://discourse.julialang.org/t/juno-fails-to-install-julia-client-0-9-4/27544/8?u=pfitzseb) and [here](https://github.com/JunoLab/atom-julia-client/issues/590).
